 CREATE TABLE "SYSTEM"."STUDENT_REGISTRATION" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"USERNAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"COMMUNITY" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"ABOUTYOU" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
}